export enum IconsArray {
  backend = 'backend',
  burger = 'burger',
  checked = 'checked',
  close = 'close',
  crea = 'crea',
  design = 'design',
  frontend = 'frontend',
  logo = 'logo',
  mobile = 'mobile',
  py = 'py',
  rawLeft = 'rawLeft',
  rawRight = 'rawRight',
  rectangleBg = 'rectangleBg',
}
